site_name: TXRX Derail Light Manual
site_url: https://niell-ion.github.io/derail-docs/
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
  features:
    - navigation.footer
company: Transmit Receive Labs Inc.
nav:
  - Home: index.md
  - System Overview: derail_overview.md
  - Setup: derail_setup.md
  - Operation: derail_operation.md
  - Maintenance: derail_maintenance.md
  - Troubleshooting: derail_troubleshooting.md
plugins:
  - to-pdf:
      output_path: document.pdf
      # enabled_if_env: ENABLE_PDF_EXPORT
markdown_extensions:
  - admonition:
  - pymdownx.details:
  - pymdownx.superfences:
  - toc:
      permalink: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
