site_name: TXRX Derail Light Manual
site_url: https://niell-ion.github.io/derail_docs
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
  features:
    - navigation.footer
nav:
  - Table of Contents: docs/derail_toc.md
  - Preface: docs/derail_preface.md
  - System Overview: docs/derail_overview.md
  - Setup: docs/derail_setup.md
  - Operation: docs/derail_operation.md
  - Maintenance: docs/derail_maintenance.md
  - Troubleshooting: docs/derail_troubleshooting.md
plugins:
  - to-pdf:
      output_path: document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
markdown_extensions:
  - admonition:
  - pymdownx.details:
  - pymdownx.superfences:
  - toc:
      permalink: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
